name: CI-Backend

on:
  pull_request:
  push:
    branches:
    - development

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: test
    needs: fmt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo test

  san-test:
    name: san-test
    needs: fmt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - run: cargo test --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: -Z sanitizer=address
          RUSTDOCFLAGS: -Z sanitizer=address

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy --all --benches --examples --tests --all-features

  docs:
    name: docs
    runs-on:  ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo doc --no-deps --document-private-items
